// Stil notu: DLI’nin mevcut koyu + mor + premium yazılım kimliğini koruyan ortak içerik sözlüğü.
export type ProductSlug = "launcher" | "client" | "core" | "connect";
export type Product = { slug: ProductSlug; name: string; eyebrow: string; shortDescription: string; description: string; detail: string; icon: string; accent: string; image?: string; features: string[] };
export const products: Product[] = [
  { slug: "launcher", name: "DLI Launcher", eyebrow: "THE DESKTOP SURFACE", shortDescription: "Your library, communities and next session — in one quiet surface.", description: "The central desktop experience for discovering, updating and launching the worlds you care about.", detail: "DLI Launcher brings the ecosystem into focus without turning the desktop into a dashboard. Every surface has a purpose: find what is next, understand what changed and step into the world with less friction.", icon: "01", accent: "#7C3AED", features: ["Unified game library", "Quiet background updates", "Contextual community access"] },
  { slug: "client", name: "DLI Client", eyebrow: "THE IN-GAME LAYER", shortDescription: "The layer between the player and the world.", description: "A focused in-game experience that keeps identity, presence and the things that matter close at hand.", detail: "DLI Client extends the product into the moment of play. It is designed to feel present, not intrusive: a clear signal when you need it, an invisible layer when you do not.", icon: "02", accent: "#8B5CF6", features: ["Low-friction presence", "Player-first context", "Designed for focus"] },
  { slug: "core", name: "DLI Core", eyebrow: "THE INFRASTRUCTURE", shortDescription: "The technology that keeps every surface connected.", description: "A dependable systems layer for identity, services and the shared logic behind the ecosystem.", detail: "DLI Core is the connective tissue beneath the experience. It gives products a common language so players, creators and communities can move through the ecosystem as one.", icon: "03", accent: "#7C3AED", features: ["Composable services", "Shared identity layer", "Built for sustainable scale"] },
  { slug: "connect", name: "DLI Connect", eyebrow: "THE SOCIAL LAYER", shortDescription: "Community tools that leave room for community.", description: "A considered social layer for finding people, sharing context and building the next part of the world together.", detail: "DLI Connect makes the human layer feel native to the products around it. It gives communities useful context without turning every interaction into noise.", icon: "04", accent: "#8B5CF6", features: ["Persistent communities", "Creator-friendly tools", "Signal over noise"] },
];
export const navItems = [{ label: "Products", href: "/products" }, { label: "Technology", href: "/technology" }, { label: "About", href: "/about" }, { label: "Documentation", href: "/documentation" }];
export const stats = [{ value: "04", label: "connected product surfaces" }, { value: "01", label: "shared ecosystem layer" }, { value: "∞", label: "ways to make it yours" }];
export const footerGroups = [
  { title: "Explore", links: [{ label: "Products", href: "/products" }, { label: "Technology", href: "/technology" }, { label: "About DLI", href: "/about" }] },
  { title: "Resources", links: [{ label: "Documentation", href: "/documentation" }, { label: "Contact", href: "/contact" }, { label: "Status", href: "/documentation#status" }] },
  { title: "Elsewhere", links: [{ label: "GitHub", href: "https://github.com" }, { label: "Discord", href: "https://discord.com" }, { label: "Privacy", href: "/about#privacy" }] },
];

