// Stil notu: Contact, yüksek kontrastlı form yüzeyi ve sakin microcopy ile DLI’nin teknik ama erişilebilir sesini sürdürür.
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowUpRight, CheckCircle2, Mail } from "lucide-react";
import { useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { Link } from "wouter";
import { z } from "zod";
import { PageHero } from "@/components/page-hero";
import { Reveal } from "@/components/reveal";
const contactSchema = z.object({ name: z.string().min(2, "Name is required"), email: z.string().email("Enter a valid email"), topic: z.string().min(2, "Choose a topic"), message: z.string().min(12, "Tell us a little more") });
type ContactValues = z.infer<typeof contactSchema>;
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}{error && <small>{error}</small>}</label>; }
export default function Contact() { const [submitted, setSubmitted] = useState(false); const { register, handleSubmit, formState: { errors, isSubmitting }, reset } = useForm<ContactValues>({ resolver: zodResolver(contactSchema) }); const onSubmit = async (values: ContactValues) => { void values; await new Promise((resolve) => setTimeout(resolve, 450)); setSubmitted(true); reset(); }; return <div><PageHero index="05" eyebrow="CONTACT" title="Bring us the next layer." description="Tell us what you are building, where the experience gets stuck or what you want to make feel closer." /><section className="section-space"><div className="container grid gap-14 lg:grid-cols-[0.7fr_1.3fr]"><Reveal><div><div className="flex h-11 w-11 items-center justify-center border border-violet-400/30 bg-violet-400/10 text-violet-300"><Mail size={19} /></div><h2 className="mt-7 text-3xl font-semibold tracking-[-0.05em] text-white">Start a useful conversation.</h2><p className="mt-5 max-w-sm text-base leading-7 text-slate-400">We read every note. Product ideas, partnerships and thoughtful questions all have a place here.</p><Link href="mailto:hello@dlistudios.com" className="text-link mt-8">hello@dlistudios.com <ArrowUpRight size={15} /></Link></div></Reveal><Reveal delay={0.08}><div className="form-card">{submitted ? <div className="flex min-h-[360px] flex-col items-center justify-center text-center"><CheckCircle2 size={38} className="text-violet-300" /><h2 className="mt-6 text-2xl font-semibold tracking-[-0.04em] text-white">Message received.</h2><p className="mt-3 max-w-sm text-sm leading-6 text-slate-400">Thanks for giving us something real to think about. We’ll be in touch.</p><button type="button" className="text-link mt-8" onClick={() => setSubmitted(false)}>Send another note <ArrowUpRight size={14} /></button></div> : <form onSubmit={handleSubmit(onSubmit)} noValidate><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" error={errors.name?.message}><input {...register("name")} placeholder="Your name" /></Field><Field label="Email" error={errors.email?.message}><input type="email" {...register("email")} placeholder="you@company.com" /></Field></div><Field label="Topic" error={errors.topic?.message}><select {...register("topic")} defaultValue=""><option value="" disabled>Select one</option><option value="partnership">Partnership</option><option value="product">Product</option><option value="community">Community</option><option value="other">Something else</option></select></Field><Field label="Message" error={errors.message?.message}><textarea {...register("message")} placeholder="What are you thinking about?" rows={6} /></Field><button type="submit" className="button button--primary mt-2" disabled={isSubmitting}>{isSubmitting ? "Sending…" : "Send message"} <ArrowUpRight size={16} /></button></form>}</div></Reveal></div></section></div>; }

