// Stil notu: Documentation, ürün yüzeylerinden ayrışan ama aynı dark + purple sistem içinde kalan okunabilir bir çalışma alanıdır.
import { ArrowUpRight, BookOpen, ChevronDown, Code2, FileText, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { PageHero } from "@/components/page-hero";
import { Reveal } from "@/components/reveal";
const docs = [{ title: "Getting started", detail: "Understand the DLI product model and find your way around.", icon: BookOpen }, { title: "Core concepts", detail: "Identity, services and the connective tissue underneath.", icon: Code2 }, { title: "Product surfaces", detail: "Build experiences that feel native to the ecosystem.", icon: FileText }, { title: "Trust & privacy", detail: "The principles that guide how we handle the human layer.", icon: ShieldCheck }];
const questions = [["What is DLI Studios?", "DLI Studios builds the infrastructure, software and experiences that connect players, creators and communities."], ["Who is DLI for?", "DLI is for players who want less friction, creators who want better tools and communities that want more signal than noise."], ["Can I build on top of DLI?", "The ecosystem is being designed with extensibility in mind. Documentation will grow alongside the products."]];
function FAQItem({ question, answer }: { question: string; answer: string }) { const [open, setOpen] = useState(false); return <div className="border-b border-white/8"><button type="button" className="faq-trigger" onClick={() => setOpen((value) => !value)} aria-expanded={open}><span>{question}</span><ChevronDown size={17} className={open ? "rotate-180 text-violet-300" : "text-slate-600"} /></button>{open && <div className="pb-6 pr-8 text-sm leading-6 text-slate-400">{answer}</div>}</div>; }
export default function Documentation() { return <div><PageHero index="04" eyebrow="DOCUMENTATION" title="The system, in plain language." description="A growing reference for the products and ideas behind DLI Studios. Start with the model, then go deeper when you need to." /><section className="section-space"><div className="container"><div className="grid gap-5 md:grid-cols-2">{docs.map((doc, index) => { const Icon = doc.icon; return <Reveal key={doc.title} delay={index * 0.05}><Link href="#faq" className="doc-card"><Icon size={22} className="text-violet-300" /><div><h2>{doc.title}</h2><p>{doc.detail}</p><span className="text-link mt-6">Read the guide <ArrowUpRight size={14} /></span></div></Link></Reveal>; })}</div></div></section><section id="faq" className="section-space border-y border-white/8 bg-[#0B0B10]"><div className="container grid gap-12 lg:grid-cols-[0.7fr_1fr]"><Reveal><p className="eyebrow text-violet-300">COMMON QUESTIONS</p><h2 className="mt-5 text-3xl font-semibold tracking-[-0.05em] text-white sm:text-5xl">A little more context.</h2></Reveal><Reveal delay={0.08}><div>{questions.map(([question, answer]) => <FAQItem key={question} question={question} answer={answer} />)}</div></Reveal></div></section><section id="status" className="section-space"><div className="container"><div className="status-card"><span className="signal-dot" /><div><p className="eyebrow text-violet-300">SYSTEM STATUS</p><h2 className="mt-3 text-xl font-semibold tracking-[-0.03em] text-white">All systems are moving forward.</h2></div><span className="ml-auto text-xs uppercase tracking-[0.16em] text-slate-500">Operational</span></div></div></section></div>; }

