// Stil notu: Ana sayfa DLI’yi %90 premium teknoloji şirketi, %10 oyun ekosistemi olarak sunar; ürün kompozisyonu efektlerden önce gelir.
import { ArrowDownRight, ArrowUpRight, Blocks, Cpu, Layers3, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { Reveal } from "@/components/reveal";
import { SectionLabel } from "@/components/section-label";
import { ProductMockup, ProductSurface } from "@/components/product-surface";
import { products, stats } from "@/lib/site";

export default function Home() {
  return <div>
    <section className="hero-section"><div className="hero-section__ambient" /><div className="container relative z-10 grid min-h-[720px] items-end gap-14 pb-16 pt-28 lg:grid-cols-[0.85fr_1.15fr] lg:pb-24 lg:pt-32">
      <div className="max-w-xl"><Reveal><div className="eyebrow mb-7 flex items-center gap-3 text-violet-300"><span className="signal-dot" /> DLI STUDIOS / ECOSYSTEM 01</div><h1 className="display-title display-title--hero">The ecosystem behind your game.</h1><p className="mt-8 max-w-md text-base leading-7 text-slate-400 sm:text-lg">We build the infrastructure, software and experiences that connect players, creators and communities.</p><div className="mt-10 flex flex-wrap items-center gap-4"><Link href="/products" className="button button--primary">Explore the ecosystem <ArrowUpRight size={16} /></Link><Link href="/technology" className="button button--ghost">See how it works <ArrowDownRight size={16} /></Link></div></Reveal></div>
      <Reveal delay={0.1} className="relative lg:translate-x-10"><div className="hero-product-frame"><div className="hero-product-frame__topline"><span>DLI LAUNCHER</span><span>CONNECTED / 01</span></div><ProductMockup product={products[0]} /><div className="hero-product-frame__caption"><span>Designed for the way you play.</span><span className="text-violet-300">01 — 04</span></div></div></Reveal>
    </div><div className="hero-section__scroll"><span>Scroll to explore</span><span className="hero-section__scroll-line" /></div></section>

    <section className="section-space"><div className="container"><div className="grid gap-10 lg:grid-cols-[0.3fr_1fr]"><SectionLabel index="01">THE ECOSYSTEM</SectionLabel><div><Reveal><h2 className="section-title max-w-3xl">Four surfaces.<br /><span className="text-slate-500">One shared layer.</span></h2></Reveal><Reveal delay={0.05}><p className="mt-7 max-w-xl text-base leading-7 text-slate-400">DLI is not one destination. It is the layer that lets your library, your identity and your community move with you.</p></Reveal><div className="mt-14 grid gap-5 sm:grid-cols-2">{products.map((product, index) => <Reveal key={product.slug} delay={index * 0.04}><ProductSurface product={product} large={index === 0} /></Reveal>)}</div></div></div></div></section>

    <section className="section-space section-space--tight border-y border-white/8 bg-[#0B0B10]"><div className="container"><div className="grid gap-10 lg:grid-cols-[0.3fr_1fr]"><SectionLabel index="02">THE NUMBERS</SectionLabel><div className="stats-grid">{stats.map((stat) => <div key={stat.label} className="stat-block"><span className="stat-block__value">{stat.value}</span><span className="stat-block__label">{stat.label}</span></div>)}</div></div></div></section>

    <section className="section-space overflow-hidden"><div className="container"><div className="grid gap-12 lg:grid-cols-[0.3fr_1fr]"><SectionLabel index="03">THE CORE</SectionLabel><div className="grid items-end gap-12 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><h2 className="section-title">Built for the layer between the player and the world.</h2><p className="mt-7 text-base leading-7 text-slate-400">Every DLI product speaks the same language. That means less friction for players and more room for creators to build what comes next.</p><Link href="/technology" className="text-link mt-8">Explore the technology <ArrowUpRight size={15} /></Link></Reveal><Reveal delay={0.08}><div className="architecture-card"><div className="architecture-card__header"><span>LIVE SYSTEM MAP</span><span className="text-violet-300">STABLE</span></div><div className="architecture-card__line" />{["Launcher", "DLI Core", "Services / API", "Community"].map((layer, index) => <div key={layer} className="architecture-row"><span className="architecture-row__index">0{index + 1}</span><span>{layer}</span><span className="architecture-row__signal" /></div>)}</div></Reveal></div></div></div></section>

    <section className="section-space section-space--tight border-y border-white/8 bg-[#0B0B10]"><div className="container"><div className="grid gap-8 lg:grid-cols-3"><Reveal><div className="feature-card"><Layers3 size={22} className="text-violet-300" /><h3>One connected language</h3><p>Products that feel like parts of the same world, not separate tabs.</p></div></Reveal><Reveal delay={0.06}><div className="feature-card"><Cpu size={22} className="text-violet-300" /><h3>Quietly powerful</h3><p>Infrastructure that does the hard work without getting in the way.</p></div></Reveal><Reveal delay={0.12}><div className="feature-card"><UsersRound size={22} className="text-violet-300" /><h3>Made for people</h3><p>Tools for players, creators and communities to shape what comes next.</p></div></Reveal></div></div></section>

    <section className="cinematic-section"><div className="cinematic-world"><div className="cinematic-world__horizon" /><div className="cinematic-world__grid" /><div className="cinematic-world__surface"><span>CLIENT / WORLD CONTEXT</span><b>CONNECTED</b></div></div><div className="cinematic-section__overlay" /><div className="container relative z-10 flex min-h-[560px] items-end pb-16 sm:pb-24"><div className="max-w-xl"><div className="eyebrow text-violet-300">A WORLD IN CONTEXT</div><h2 className="mt-5 text-4xl font-semibold tracking-[-0.06em] text-white sm:text-6xl">Gaming is the world.<br /><span className="text-slate-500">DLI is the layer.</span></h2><Link href="/about" className="button button--ghost mt-9">What we believe <ArrowUpRight size={16} /></Link></div></div></section>

    <section className="section-space"><div className="container"><div className="cta-panel"><div className="cta-panel__grid" /><div className="relative z-10 max-w-2xl"><div className="eyebrow text-violet-300">START WITH THE SURFACE</div><h2 className="mt-5 text-4xl font-semibold tracking-[-0.06em] text-white sm:text-6xl">Make the next session feel closer.</h2><p className="mt-6 max-w-md text-base leading-7 text-slate-400">Explore the products that make DLI an ecosystem, not just another destination.</p><Link href="/products" className="button button--primary mt-9">Explore products <ArrowUpRight size={16} /></Link></div><Blocks className="cta-panel__icon" size={160} strokeWidth={0.35} /></div></div></section>
  </div>;
}
