// Stil notu: Teknoloji sayfası DLI Core’u görsel rezervine değil, Purple Signal Line ile bağlanan canlı bir sistem omurgasına dönüştürür.
import { ArrowUpRight, GitBranch, ShieldCheck, Waypoints } from "lucide-react";
import { Link } from "wouter";
import { PageHero } from "@/components/page-hero";
import { Reveal } from "@/components/reveal";

const layers = [{ name: "Launcher", detail: "A clear desktop entry point", icon: "01" }, { name: "DLI Core", detail: "Shared identity and logic", icon: "02" }, { name: "Services / API", detail: "Composable systems underneath", icon: "03" }, { name: "Community", detail: "The human layer on top", icon: "04" }];

function SystemMap() { return <div className="technology-visual system-map-visual"><div className="system-map-visual__top"><span>CORE / SYSTEM MAP</span><span className="text-violet-300">CONNECTED / STABLE</span></div><div className="system-map-visual__body"><div className="system-map-visual__backdrop" />{layers.map((layer, index) => <div className="system-map-node" key={layer.name} style={{ ["--node-index" as string]: index }}><span>{layer.icon}</span><b>{layer.name}</b><i /></div>)}</div><div className="technology-visual__label"><span>SHARED IDENTITY / SERVICES / PRESENCE</span><span className="text-violet-300">DLI CORE</span></div></div>; }

export default function Technology() { return <div><PageHero index="02" eyebrow="THE TECHNOLOGY" title="A system that stays out of the way." description="The best infrastructure is felt in the experience, not in the interface. DLI Core gives every product a shared language and every community room to grow." /><section className="section-space"><div className="container"><Reveal><SystemMap /></Reveal><div className="mt-24 grid gap-12 lg:grid-cols-[0.7fr_1fr]"><Reveal><p className="eyebrow text-violet-300">THE ARCHITECTURE</p><h2 className="mt-5 text-3xl font-semibold tracking-[-0.05em] text-white sm:text-5xl">One layer. Many ways through.</h2></Reveal><div className="space-y-0">{layers.map((layer, index) => <Reveal key={layer.name} delay={index * 0.06}><div className="tech-layer"><span className="tech-layer__index">{layer.icon}</span><div><h3>{layer.name}</h3><p>{layer.detail}</p></div><span className="tech-layer__line" /></div></Reveal>)}</div></div></div></section><section className="section-space border-y border-white/8 bg-[#0B0B10]"><div className="container"><div className="grid gap-5 md:grid-cols-3"><Reveal><div className="feature-card"><GitBranch size={22} className="text-violet-300" /><h3>Composable by default</h3><p>Services that can evolve without asking the whole system to move at once.</p></div></Reveal><Reveal delay={0.06}><div className="feature-card"><ShieldCheck size={22} className="text-violet-300" /><h3>Trust at the center</h3><p>Identity and presence designed as foundations, not afterthoughts.</p></div></Reveal><Reveal delay={0.12}><div className="feature-card"><Waypoints size={22} className="text-violet-300" /><h3>Made to connect</h3><p>Every surface becomes more useful because the layers speak the same language.</p></div></Reveal></div></div></section><section className="section-space"><div className="container flex flex-col gap-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-violet-300">THE NEXT LAYER</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-[-0.05em] text-white sm:text-5xl">Start with the products built on top.</h2></div><Link href="/products" className="text-link">View products <ArrowUpRight size={15} /></Link></div></section></div>; }
